AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: A Centre for Messages

Resources:
  ViewMessagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/get/
      Handler: view_messages.handler #specifying which file and function
      Runtime: python3.9
      Policies:
        - AmazonS3ReadOnlyAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /view_messages
            Method: get
  SendMessageFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/post/
      Handler: post_message.handler #specifying which file and function
      Runtime: python3.9
      Policies:
        - AmazonS3FullAccess
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /send_message
            Method: post
  BucketOfMessages:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: s3-message-storage
